// <auto-generated />
using GloiathNationalBank.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GloiathNationalBank.Data.Migrations
{
    [DbContext(typeof(GloiathNationalBankContext))]
    [Migration("20230523202120_AddCachedTransaction")]
    partial class AddCachedTransaction
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("GloiathNationalBank.Models.CachedTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsUpToDate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CachedTransactions");
                });

            modelBuilder.Entity("GloiathNationalBank.Models.ProductSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MyProperty")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductSummaries");
                });

            modelBuilder.Entity("GloiathNationalBank.Models.Rate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("RateValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            From = "EUR",
                            RateValue = 1.359m,
                            To = "USD"
                        },
                        new
                        {
                            Id = 2,
                            From = "CAD",
                            RateValue = 0.732m,
                            To = "EUR"
                        },
                        new
                        {
                            Id = 3,
                            From = "USD",
                            RateValue = 0.736m,
                            To = "EUR"
                        },
                        new
                        {
                            Id = 4,
                            From = "EUR",
                            RateValue = 1.366m,
                            To = "CAD"
                        });
                });

            modelBuilder.Entity("GloiathNationalBank.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10.00m,
                            Currency = "USD",
                            Sku = "T2006"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 34.57m,
                            Currency = "CAD",
                            Sku = "M2007"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 17.95m,
                            Currency = "USD",
                            Sku = "R2008"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 7.63m,
                            Currency = "EUR",
                            Sku = "T2006"
                        },
                        new
                        {
                            Id = 5,
                            Amount = 21.23m,
                            Currency = "USD",
                            Sku = "B2009"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
